### ISSUE TITLE
blog post linked in readme is dead

### ISSUE THREAD

**Issue by Pagwin2** [abbycin/preemptive#1]
was kinda hoping to read the blog post for more info on what was tried/thoughts, regardless if the blog isn't coming back it would make sense to remove the link in the README

**Comment by abbycin** [comment]
@Pagwin-Fedora [http://note.isliberty.me/article/65](http://note.isliberty.me/article/65) here is the new link (if you can read Chinese， BTW, the conclusion is incorrect, AFAIK, golang has recently added preemptive scheduling support)

**Comment by Pagwin2** [comment]
ah, okay good to know thanks
